### ISSUE TITLE
Unable to build: Failed to execute goal on project webkarma

### ISSUE THREAD

**Issue by kicOLD** [usc-isi-i2/szeke#11]
PLease se my maven output .. 

~/karma/Web-Karma-Public# mvn -Djetty.port=5555 jetty:run
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for edu.isi:webkarma:war:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.healthmarketscience.jackcess:jackcess:jar -> version 1.2.10 vs 1.2.4 @ line 185, column 21
[WARNING] 'dependencies.dependency.systemPath' for uk.ac.shef.wit.simmetrics:simmetrics:jar should not point at files within the project directory, ${project.basedir}/lib/simmetrics_jar_v1_6_2_d07_02_07.jar will be unresolvable by dependent projects @ line 251, column 19
[WARNING] 'dependencies.dependency.systemPath' for com.jspsmart.upload:jspsmartupload:jar should not point at files within the project directory, ${project.basedir}/lib/jsmartupload.jar will be unresolvable by dependent projects @ line 268, column 19
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.hadoop:hadoop-core:jar -> version 0.20.2 vs 0.20.205.0 @ line 295, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 413, column 16
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ISI Karma Maven Webapp 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:8.0.3.v20111011:run (default-cli) @ webkarma >>>
[WARNING] The POM for de.micromata.jak:JavaAPIforKml:jar:2.2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.465s
[INFO] Finished at: Thu Jun 27 14:32:11 CEST 2013
[INFO] Final Memory: 8M/152M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project webkarma: Could not resolve dependencies for project edu.isi:webkarma:war:0.0.1-SNAPSHOT: Failure to find de.micromata.jak:JavaAPIforKml:jar:2.2.0-SNAPSHOT in http://download.osgeo.org/webdav/geotools/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by shubhamg** [comment]
Fixed in the latest commit

**Comment by kicOLD** [comment]
thx!
