### ISSUE TITLE
Offline RDF generation

### ISSUE THREAD

**Issue by FrenkT** [usc-isi-i2/szeke#13]
Hi, I'm following this ( https://github.com/InformationIntegrationGroup/Web-Karma-Public#frequently-asked-questions ) instructions to generate RDF offile but I can't make it work. This is an example of my command and errors:

frank@ubuntu:~/programs/Web-Karma-Public-master$ mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineDbRdfGenerator" -Dexec.args="--sourcetype DB -dbtype MySQL --hostname localhost --username frank --password *****\* --portnumber 3306 --dbname test --tablename park_replica --modelfilepath \"/home/frank/programs/Web-Karma-Public-master/src/main/webapp/publish/R2RML/WSP1VW1-park_replica-model.ttl\" --outputfile tmp/triple.rdf"
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building ISI Karma Maven Webapp 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ webkarma >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ webkarma <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ webkarma ---
[WARNING] 
java.lang.ClassNotFoundException: edu.isi.karma.rdf.OfflineDbRdfGenerator
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
    at java.lang.Thread.run(Thread.java:724)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.537s
[INFO] Finished at: Sat Oct 05 12:10:58 CEST 2013
[INFO] Final Memory: 11M/151M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project webkarma: An exception occured while executing the Java class. edu.isi.karma.rdf.OfflineDbRdfGenerator -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by szeke** [comment]
Yup, it is broken. We are looking into it. You can see our progress at
https://webkarma.atlassian.net/browse/WK-2 (we also switched to a public
JIRA issue tracker)

BTW, we switched repository to
https://github.com/InformationIntegrationGroup/Web-Karma
When we fix this bug, you need to retrieve the new version from Web-Karma,
not Web-Karma-Public

Pedro

Pedro

**Comment by dkapoor** [comment]
This should work now.
