### ISSUE TITLE
Weka is incompatible with project license

### ISSUE THREAD

**Issue by tfmorris** [usc-isi-i2/szeke#2]
The Weka machine learning package is licensed under GPL v2 (and the trunk has switched to GPL v3), so it's not compatible with the Apache 2 license listed on http://www.isi.edu/integration/karma/

Either the project license needs to be changed or Weka removed.  I'd recommend the latter and that's what I've done in my fork.

**Comment by shubhamg** [comment]
Thanks for letting us know. I will discuss it in my team to resolve this issue.

**Comment by shubhamg** [comment]
Removed from the dependencies.

**Comment by tfmorris** [comment]
Thanks.  Although it was commented out of the POM, the JAR is still there.  I opened pull request #5 to delete it (and the unused jGraphT JAR since that dependency is now managed by Maven)
