### ISSUE TITLE
Don't store data files in source tree

### ISSUE THREAD

**Issue by tfmorris** [usc-isi-i2/szeke#9]
It looks like the server is configured to just store files in the same tree as the source files.  It would be much better to have this a) be configurable and b) have the default be someplace outside of the source tree.

Some example files from my .gitignore include:

lastJsonImport.json (in top level directory)
src/main/webapp/UserUploadedFiles/*
src/main/webapp/UserPrefs/*
src/main/webapp/CRF_Models/*
src/main/webapp/publish/AutoOntology/*
src/main/webapp/publish/CSV/*
src/main/webapp/repository/dataset/*

**Comment by shubhamg** [comment]
All these paths are configurable through a single parameter in web.xml. These can be easily moved out of the source code and the code will still run fine.

**Comment by tfmorris** [comment]
Thanks for the tip.  Does that include lastJsonImport.json which is not in the tree rooted at src/main/webapp where USER_DIRECTORY_PATH points?  A better default value for USER_DIRECTORY_PATH might be "data" or "user_data" or some similarly named directory which is outside the src tree.

**Comment by dkapoor** [comment]
We not have a Karma User Home directory that stores these files. You could always change the User Home folder from the footer of Karma UI.
